services:
  backend:
    build: .
    container_name: fastapi_bot
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - ../pg_data_topsme_bot:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  pg_data_topsme_bot:
